/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin._task;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.*;
import weaver.file.FileUpload;
import java.util.*;
import weaver.hrm.*;
import weaver.systeminfo.*;
import weaver.general.StaticObj;
import weaver.general.Util;
import weaver.hrm.settings.RemindSettings;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class _getmorefb__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.hrm.resource.ResourceComInfo rc;
      rc = (weaver.hrm.resource.ResourceComInfo) pageContext.getAttribute("rc");
      if (rc == null) {
        rc = new weaver.hrm.resource.ResourceComInfo();
        pageContext.setAttribute("rc", rc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	
	response.setHeader("cache-control", "no-cache");
	response.setHeader("pragma", "no-cache");
	response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
	

	User user = HrmUserVarify.getUser (request , response) ;
	if(user == null)  return ;
	Log logger= LogFactory.getLog(this.getClass());
	String isIE = (String)session.getAttribute("browser_isie");

      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.conn.RecordSet rs2;
      rs2 = (weaver.conn.RecordSet) pageContext.getAttribute("rs2");
      if (rs2 == null) {
        rs2 = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs2", rs2);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.workrelate.util.CommonTransUtil cmutil;
      cmutil = (weaver.workrelate.util.CommonTransUtil) pageContext.getAttribute("cmutil");
      if (cmutil == null) {
        cmutil = new weaver.workrelate.util.CommonTransUtil();
        pageContext.setAttribute("cmutil", cmutil);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
	try{
		FileUpload fu = new FileUpload(request);
		String taskId = Util.null2String(fu.getParameter("taskId"));
		int pageNum = Util.getIntValue(fu.getParameter("pageNum"),1);
		String sql = " from TM_TaskFeedback where taskid="+taskId;
		String orderBySql = " order by createdate desc,createtime desc";
		String orderBySql2 = " order by createdate,createtime";
		int iTotal = 0;
		rs.executeSql("select count(*)"+sql);
		if(rs.next()){
			iTotal = rs.getInt(1);
		}
		int totalpage = 1;
		if(iTotal>0){
			int _pagesize = 5;
			totalpage = iTotal / _pagesize;
			if(iTotal % _pagesize >0) totalpage += 1;
			int iNextNum = pageNum * _pagesize;
			int ipageset = _pagesize;
			if(iTotal - iNextNum + _pagesize < _pagesize) ipageset = iTotal - iNextNum + _pagesize;
			if(iTotal < _pagesize) ipageset = iTotal;
			if(rs.getDBType().equals("oracle")){
				sql = "select *"+ sql+orderBySql;
				sql = "select A.*,rownum rn from (" + sql + ") A where rownum <= " + iNextNum;
				sql = "select B.* from (" + sql + ") B where rn > " + (iNextNum - _pagesize);
			}else{
				sql = "select top " + ipageset +" A.* from (select top "+ iNextNum + "*"+ sql +orderBySql+") A "+orderBySql2;
				sql = "select top " + ipageset +" B.* from (" + sql + ") B "+orderBySql;
			}
			rs.execute(sql);
			while(rs.next()){
				int id = rs.getInt("id");
				String replyid = Util.null2String(rs.getString("replyid"));

      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rc.getLastname(rs.getString("hrmid")) ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((Util.null2String(rs.getString("createdate")) ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((Util.null2String(rs.getString("createtime")) ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((Util.null2String(rs.getString("content")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if(!"".equals(rs.getString("docids"))){ 
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((cmutil.getDocNameForMobile(rs.getString("docids")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if(!"".equals(rs.getString("wfids"))){ 
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((cmutil.getRequestNameForMobile(rs.getString("wfids")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if(!"".equals(rs.getString("crmids"))){ 
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((cmutil.getCustomerForMobile(rs.getString("crmids")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if(!"".equals(rs.getString("projectids"))){ 
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((cmutil.getProjectForMobile(rs.getString("projectids")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if(!"".equals(rs.getString("fileids"))){ 
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((cmutil.getFileNameForMobile(rs.getString("fileids")) ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      } 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      
						  //\u8bfb\u53d6\u56de\u590d\u4fe1\u606f
						  if(!replyid.equals("")){ 
							rs2.executeSql("select id,content,hrmid,docids,wfids,crmids,projectids,meetingids,fileids,createdate,createtime,replyid from TM_TaskFeedback where id="+replyid);
							if(rs2.next()){
						
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((rc.getLastname(rs2.getString("hrmid")) ));
      out.write(' ');
      out.print((Util.null2String(rs2.getString("createdate")) ));
      out.write(' ');
      out.print((Util.null2String(rs2.getString("createtime")) ));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((Util.null2String(rs2.getString("content")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      if(!"".equals(rs2.getString("docids"))){ 
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((cmutil.getDocNameForMobile(rs2.getString("docids")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if(!"".equals(rs2.getString("wfids"))){ 
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((cmutil.getRequestNameForMobile(rs2.getString("wfids")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if(!"".equals(rs2.getString("crmids"))){ 
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((cmutil.getCustomerForMobile(rs2.getString("crmids")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if(!"".equals(rs2.getString("projectids"))){ 
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((cmutil.getProjectForMobile(rs2.getString("projectids")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if(!"".equals(rs2.getString("fileids"))){ 
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((cmutil.getFileNameForMobile(rs2.getString("fileids")) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      } 
      out.write(_jsp_string23, 0, _jsp_string23.length);
      	} 
      out.write(_jsp_string9, 0, _jsp_string9.length);
      } 
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((id ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      			}
		}
		if(pageNum==1){

      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((totalpage));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      	
		}
	}catch(Exception e){
		out.print("<tr id='gettr'><td class='data' align='center'>\u83b7\u53d6\u66f4\u591a\u53cd\u9988\u5931\u8d25</td></tr>");	
	}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/task/getMoreFb.jsp"), -9205436100555082328L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("page/maint/common/initNoCache.jsp"), 3270256153856711871L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string15;
  private final static char []_jsp_string26;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string22;
  private final static char []_jsp_string25;
  private final static char []_jsp_string27;
  private final static char []_jsp_string3;
  private final static char []_jsp_string24;
  private final static char []_jsp_string16;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string18;
  private final static char []_jsp_string12;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string20;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string23;
  private final static char []_jsp_string19;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  static {
    _jsp_string15 = "</div>\r\n							<div class=\"feedbackrelate2\">\r\n								<div>".toCharArray();
    _jsp_string26 = "	\r\n	<input type=\"hidden\" id=\"fbTotalPage\" value=\"".toCharArray();
    _jsp_string10 = "\r\n						<div class=\"relatetitle\">\u76f8\u5173\u6d41\u7a0b\uff1a".toCharArray();
    _jsp_string21 = "\r\n								<div class=\"relatetitle2\">\u76f8\u5173\u9879\u76ee\uff1a".toCharArray();
    _jsp_string22 = "\r\n								<div class=\"relatetitle2\">\u76f8\u5173\u9644\u4ef6\uff1a".toCharArray();
    _jsp_string25 = "')\">\u56de\u590d</a>\r\n					</td>\r\n				</tr>\r\n			</table>\r\n		</div>\r\n	</td>\r\n</tr>\r\n\r\n".toCharArray();
    _jsp_string27 = "\"/>	\r\n	".toCharArray();
    _jsp_string3 = "				\r\n<tr>\r\n	<td>\r\n		<div class=\"feedbackshow\">\r\n			<table width=\"100%\" class=\"fbShowTable\">\r\n			<tr>\r\n				<td width=\"40%\" class=\"date\">".toCharArray();
    _jsp_string24 = "\r\n						\r\n					</div>\r\n				</td>\r\n			</tr>\r\n			<tr>\r\n				<td colspan=\"2\" style=\"text-align:right;\">\r\n					<a href=\"javascript:doReply('".toCharArray();
    _jsp_string16 = "</div>\r\n								".toCharArray();
    _jsp_string5 = "&nbsp;\r\n					".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n				</td>\r\n			</tr>\r\n			<tr>\r\n				<td colspan=\"2\">\r\n					<div class=\"feedbackrelate\">\r\n						<div>".toCharArray();
    _jsp_string7 = "</div>\r\n						".toCharArray();
    _jsp_string18 = "\r\n								".toCharArray();
    _jsp_string12 = "\r\n						<div class=\"relatetitle\">\u76f8\u5173\u9879\u76ee\uff1a".toCharArray();
    _jsp_string13 = "\r\n						<div class=\"relatetitle\">\u76f8\u5173\u9644\u4ef6\uff1a".toCharArray();
    _jsp_string17 = "\r\n								<div class=\"relatetitle2\">\u76f8\u5173\u6587\u6863\uff1a".toCharArray();
    _jsp_string20 = "\r\n								<div class=\"relatetitle2\">\u76f8\u5173\u5ba2\u6237\uff1a".toCharArray();
    _jsp_string9 = "\r\n						".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string23 = "\r\n							</div>\r\n						</div>\r\n						".toCharArray();
    _jsp_string19 = "\r\n								<div class=\"relatetitle2\">\u76f8\u5173\u6d41\u7a0b\uff1a".toCharArray();
    _jsp_string4 = "</td>\r\n				<td width=\"60%\" class=\"date\" style=\"text-align:right;\">\r\n					".toCharArray();
    _jsp_string8 = "\r\n						<div class=\"relatetitle\">\u76f8\u5173\u6587\u6863\uff1a".toCharArray();
    _jsp_string11 = "\r\n						<div class=\"relatetitle\">\u76f8\u5173\u5ba2\u6237\uff1a".toCharArray();
    _jsp_string14 = "\r\n						<div class=\"fbreply\">\r\n							<div class=\"feedbackinfo2\">@ ".toCharArray();
  }
}
