/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin._task;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.URLDecoder;
import java.util.*;
import weaver.hrm.*;
import weaver.systeminfo.*;
import weaver.general.StaticObj;
import weaver.general.Util;
import weaver.hrm.settings.RemindSettings;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class _noright__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	
	response.setHeader("cache-control", "no-cache");
	response.setHeader("pragma", "no-cache");
	response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
	

	User user = HrmUserVarify.getUser (request , response) ;
	if(user == null)  return ;
	Log logger= LogFactory.getLog(this.getClass());
	String isIE = (String)session.getAttribute("browser_isie");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.resource.ResourceComInfo rc;
      rc = (weaver.hrm.resource.ResourceComInfo) pageContext.getAttribute("rc");
      if (rc == null) {
        rc = new weaver.hrm.resource.ResourceComInfo();
        pageContext.setAttribute("rc", rc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	String clienttype = Util.null2String((String)request.getParameter("clienttype"));
	String clientlevel = Util.null2String((String)request.getParameter("clientlevel"));
	String module=Util.null2String((String)request.getParameter("module"));
	String scope=Util.null2String((String)request.getParameter("scope"));

	String taskId = Util.null2String(request.getParameter("taskId"));
	
	rs.executeSql("select principalid,creater from TM_TaskInfo where id="+taskId+" and (deleted=0 or deleted is null)");
	if(rs.getCounts()==0) return;
	rs.next();
	
	String principalid = rc.getLastname(Util.null2String(rs.getString("principalid")));
	String creater = rc.getLastname(Util.null2String(rs.getString("creater")));
	

      out.write(_jsp_string2, 0, _jsp_string2.length);
      if("".equals(clienttype)||clienttype.equals("Webclient")){
      out.write(_jsp_string3, 0, _jsp_string3.length);
      }
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((creater ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if(!principalid.equals("") && !principalid.equals(creater)){ 
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((principalid ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      } 
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((module));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((scope));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((SystemEnv.getHtmlLabelName(1290,user.getLanguage()) ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/task/NoRight.jsp"), -831992757199023986L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("page/maint/common/initNoCache.jsp"), 3270256153856711871L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("secondwev/common/head.jsp"), -3748581346628043986L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string8;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string10;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  static {
    _jsp_string8 = "&scope=".toCharArray();
    _jsp_string6 = "\r\n						\u6216\u4efb\u52a1\u8d1f\u8d23\u4eba\uff1a".toCharArray();
    _jsp_string4 = "\r\n	</style>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/secondwev/css/transbrowser.css\" />\r\n<script type='text/javascript' src=\"/secondwev/js/jQuery.transE8Browser.js\"></script>\r\n<script type='text/javascript' src=\"/js/ecology8/request/e8.browser_wev8.js\"></script>\r\n\r\n	</head>\r\n<body>\r\n	<table class=\"taskTable\" cellpadding=\"0\" cellspacing=\"0\">\r\n		<tr>\r\n			<td width=\"100%\" height=\"100%\" valign=\"top\" align=\"left\">\r\n				<div id=\"topmain\" class=\"topmain\">\r\n					<div id=\"header\">\r\n							<table style=\"width: 100%;height: 40px;\">\r\n								<tr>\r\n									<td width=\"10%\" align=\"left\" valign=\"middle\" style=\"padding-left:5px;\">\r\n										<div class=\"taskTopBtn\" onclick=\"doLeftButton()\">\u8fd4\u56de</div>\r\n									</td>\r\n									<td align=\"center\" valign=\"middle\">\r\n										<div id=\"title\">\u4efb\u52a1</div>\r\n									</td>\r\n									<td width=\"10%\" align=\"right\" valign=\"middle\" style=\"padding-right:5px;\">\r\n									&nbsp;\r\n									</td>\r\n								</tr>\r\n							</table>\r\n					</div>\r\n				</div>\r\n				<div id=\"tabblank\" class=\"tabblank\"></div>\r\n				<div id=\"list\" class=\"list\">\r\n					<div class=\"taskTips\">\r\n						\u5f88\u62b1\u6b49\uff0c\u60a8\u6682\u65f6\u6ca1\u6709\u6743\u9650\u67e5\u770b\u6b64\u4efb\u52a1\uff01<br>\r\n						\u53ef\u8054\u7cfb\u4efb\u52a1\u521b\u5efa\u4eba\uff1a".toCharArray();
    _jsp_string7 = "\u8fdb\u884c\u5206\u4eab\uff01\r\n					</div>\r\n				</div>\r\n		</td>\r\n	</tr>\r\n	</table>\r\n	<script type=\"text/javascript\">\r\n		var param = \"module=".toCharArray();
    _jsp_string3 = "\r\n			#header{display: block;}\r\n		".toCharArray();
    _jsp_string5 = "\r\n						".toCharArray();
    _jsp_string10 = "\";\r\n		}\r\n		function getRightButton(){ \r\n			return \"1, \";\r\n		}\r\n		function doRightButton(){\r\n			return \"1\";\r\n		}\r\n		function doLeftButton(){\r\n			window.location = \"/home.do\";\r\n		}\r\n	</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string9 = "\";\r\n		$(document).ready(function(){\r\n			$(\"#tabblank\").height($(\"#topmain\").height());//\u5360\u4f4dfixed\u51fa\u6765\u7684\u7a7a\u95f4\r\n		});\r\n	\r\n		function getLeftButton(){ \r\n			return \"1,".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n	<meta name=\"author\" content=\"Weaver E-Mobile Dev Group\" />\r\n	<meta name=\"description\" content=\"Weaver E-mobile\" />\r\n	<meta name=\"keywords\" content=\"weaver,e-mobile\" />\r\n	<meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0, maximum-scale=1.0\" />\r\n	<title></title>\r\n	<script type='text/javascript' src='/mobile/plugin/task/js/jquery-1.8.3.js'></script>\r\n	<script type='text/javascript' src='/mobile/plugin/task/js/task.js'></script>\r\n	<link rel=\"stylesheet\" href=\"/mobile/plugin/task/css/task.css\" />\r\n	<style type=\"text/css\">\r\n		".toCharArray();
  }
}
