/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin._5;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.*;
import weaver.general.*;
import java.util.*;
import weaver.hrm.*;
import org.apache.commons.lang.StringEscapeUtils;
import java.text.*;
import org.apache.commons.lang.time.DateFormatUtils;

public class _detail__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.mobile.plugin.ecology.service.MeetingService meetingService;
      meetingService = (weaver.mobile.plugin.ecology.service.MeetingService) pageContext.getAttribute("meetingService");
      if (meetingService == null) {
        meetingService = new weaver.mobile.plugin.ecology.service.MeetingService();
        pageContext.setAttribute("meetingService", meetingService);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
request.setCharacterEncoding("UTF-8");
response.setContentType("text/html;charset=UTF-8");

User user = HrmUserVarify.getUser(request , response);
if(user == null)  return ;

int id = Util.getIntValue((String)request.getParameter("id"));
int detailid = Util.getIntValue(request.getParameter("detailid"));
int module = Util.getIntValue(request.getParameter("module"));
int scope = Util.getIntValue(request.getParameter("scope"));

String titleurl = Util.null2String((String)request.getParameter("title"));
String title = StringEscapeUtils.escapeHtml(URLDecoder.decode(titleurl,"UTF-8"));
titleurl = StringEscapeUtils.escapeHtml(URLEncoder.encode(titleurl, "UTF-8"));

String clienttype = Util.null2String((String)request.getParameter("clienttype"));
String clientlevel = Util.null2String((String)request.getParameter("clientlevel"));

String date = Util.null2String((String)request.getParameter("date"));
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
Date selectDate = null;
try {selectDate = dateFormat.parse(date);} catch (Exception e) {selectDate = new Date();}
date = DateFormatUtils.format(selectDate,"yyyy-MM-dd");

int requestid = Util.getIntValue((String)request.getParameter("requestid"));
String fromWF = Util.null2String((String)request.getParameter("fromWF"));
fromWF = "true".equals(fromWF) ? "true" : "";
int fromRequestid = Util.getIntValue(request.getParameter("fromRequestid"), 0);

Map meeting = meetingService.getMeeting(id, user);

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((title ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((fromWF));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((requestid));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((module));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((scope));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((fromRequestid));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((module));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((scope));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((titleurl));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((date));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((fromWF));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((requestid));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((module));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((scope));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((fromRequestid));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      if (clienttype.equals("Webclient")) {
      out.write(_jsp_string13, 0, _jsp_string13.length);
      } else {
      out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((title ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      
if(meeting==null || meeting.size()<=0) {
	
      out.write(_jsp_string17, 0, _jsp_string17.length);
      
} else {
	String meetingstatus = "";
	int meetingstatusId = Util.getIntValue((String)meeting.get("meetingstatus"));
	switch(meetingstatusId) {
		case 0:
			meetingstatus = "\u8349\u7a3f";
			break;
		case 1:
			meetingstatus = "\u5f85\u5ba1\u6279";
			break;
		case 2:
			meetingstatus = "\u6b63\u5e38";
			break;
		case 3:
			meetingstatus = "\u5ba1\u6279\u9000\u56de";
			break;
		default:
			meetingstatus = "";
	}
	
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((meeting.get("name") ));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((meeting.get("begindate") ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((meeting.get("begintime") ));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((meeting.get("enddate") ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((meeting.get("endtime") ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((meeting.get("caller") ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((meeting.get("othermemberstr") ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((meeting.get("address") ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((meeting.get("customizeAddress") ));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((meetingstatus ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((meeting.get("decision") ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      
}

      out.write(_jsp_string29, 0, _jsp_string29.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/5/detail.jsp"), 4595438311613060564L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string19;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string22;
  private final static char []_jsp_string20;
  private final static char []_jsp_string17;
  private final static char []_jsp_string8;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string24;
  private final static char []_jsp_string9;
  private final static char []_jsp_string18;
  private final static char []_jsp_string29;
  private final static char []_jsp_string11;
  private final static char []_jsp_string12;
  private final static char []_jsp_string13;
  private final static char []_jsp_string25;
  private final static char []_jsp_string21;
  private final static char []_jsp_string14;
  private final static char []_jsp_string4;
  private final static char []_jsp_string27;
  private final static char []_jsp_string28;
  private final static char []_jsp_string15;
  private final static char []_jsp_string16;
  private final static char []_jsp_string26;
  private final static char []_jsp_string23;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string19 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\">\r\n		<img style=\"margin-top: 8px;\" src=\"/mobile/plugin/5/images/time_wev8.png\">\r\n		<div style=\"float:left\">".toCharArray();
    _jsp_string6 = "&scope=".toCharArray();
    _jsp_string3 = "</title>\r\n	<script type='text/javascript' src='/mobile/plugin/js/jquery/jquery_wev8.js'></script>\r\n	<style>\r\n		html, body {\r\n			font-size: 14px;\r\n			margin: 0;\r\n			padding: 0;\r\n			background-color: #EDEDED;\r\n		}\r\n		\r\n		#view_header {\r\n			width: 100%;\r\n			height:40px;\r\n			filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#FFFFFF',endColorstr='#ececec' );\r\n			background: -webkit-gradient(linear, left top, left bottom, from(#FFFFFF),to(#ECECEC) );\r\n			background: -moz-linear-gradient(top, white, #ECECEC);\r\n			border-bottom: #CCC solid 1px;\r\n			font-size:9pt;\r\n			position:relative;\r\n		}\r\n		\r\n		#view_title {\r\n			color: #336699;\r\n			font-size: 20px;\r\n			font-weight: bold;\r\n			text-align: center;\r\n			white-space: nowrap;\r\n			overflow: hidden;\r\n			text-overflow: ellipsis;\r\n		}\r\n\r\n		.line {\r\n			border-bottom: 1px solid #C5C5C5;\r\n			padding: 0;\r\n		}\r\n\r\n		img {\r\n			max-height: 15px;\r\n			max-width: 15px;\r\n			float: left;\r\n			margin-right: 10px;\r\n		}\r\n\r\n		.lines {\r\n			padding: 10px 20px;\r\n			background-color: #FFFFFF;\r\n		}\r\n\r\n		.ptitle {\r\n			float:left;\r\n			width:80px;\r\n		}\r\n\r\n		.pcontent {\r\n			padding-left: 105px;\r\n			word-wrap: break-word;\r\n			word-break: normal;\r\n		}\r\n	</style>\r\n	<script type=\"text/javascript\">\r\n	function doLeftButton() {\r\n		var fromWF = \"".toCharArray();
    _jsp_string22 = "</div>\r\n		<div style=\"clear: both;\"></div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\">\r\n		<img src=\"/mobile/plugin/5/images/person_wev8.png\">\r\n		<div class=\"ptitle\">\u53ec\u96c6\u4eba</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string20 = "<br>".toCharArray();
    _jsp_string17 = "<div style=\"width:100%;height:280px;\"><div style=\"padding:10px;\">\u65e0\u4f1a\u8bae</div></div>".toCharArray();
    _jsp_string8 = "';\r\n			return 1;\r\n		}else{\r\n			location = \"/mobile/plugin/5/meeting.jsp?module=".toCharArray();
    _jsp_string5 = "&module=".toCharArray();
    _jsp_string7 = "&fromRequestid=".toCharArray();
    _jsp_string24 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\">\r\n		<div style=\"width:15px;height:15px;float:left;margin-right: 10px;\"></div>\r\n		<div class=\"ptitle\">\u4f1a\u8bae\u5730\u70b9</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string9 = "&title=".toCharArray();
    _jsp_string18 = "\r\n	<div class=\"lines\" style=\"margin-top: 15px;\">\r\n		<img src=\"/mobile/plugin/5/images/title_wev8.png\">\r\n		<div style=\"padding-left: 25px;word-wrap: break-word;word-break: normal;\">".toCharArray();
    _jsp_string29 = "\r\n</body>\r\n</html>".toCharArray();
    _jsp_string11 = "\";\r\n			return \"0\";\r\n		}\r\n	}\r\n	\r\n	function doBack() {\r\n		var fromWF = \"".toCharArray();
    _jsp_string12 = "';\r\n			return 1;\r\n		} else {\r\n			var result = doLeftButton();\r\n			if(result==null||result==\"BACK\"){\r\n				location = \"/home.do\";\r\n			}\r\n		}\r\n	}\r\n	</script>\r\n</head>\r\n<body>\r\n	<div id=\"view_header\" style=\"".toCharArray();
    _jsp_string13 = "display:block;".toCharArray();
    _jsp_string25 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\" style=\"min-height: 32px;\">\r\n		<div style=\"width:15px;height:15px;float:left;margin-right: 10px;\"></div>\r\n		<div class=\"ptitle\">\u81ea\u5b9a\u4e49\u4f1a\u8bae\u5730\u70b9</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string21 = "</div>\r\n		<div style=\"float:left;font-size: 28px;margin: 0 35px;\">&gt;</div>\r\n		<div style=\"float:left\">".toCharArray();
    _jsp_string14 = "display:none;".toCharArray();
    _jsp_string4 = "\";\r\n		if(fromWF == \"true\"){\r\n			location = '/mobile/plugin/1/view.jsp?requestid=".toCharArray();
    _jsp_string27 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"lines\" style=\"margin-top: 15px;\">\r\n		<div style=\"width:15px;height:15px;float:left;margin-right: 10px;\"></div>\r\n		<div class=\"ptitle\">\u63cf\u8ff0</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string28 = "&nbsp;</div>\r\n	</div>\r\n	".toCharArray();
    _jsp_string15 = "\">\r\n		<a href=\"javascript:doBack();\">\r\n			<div style=\"position:absolute;left:5px;top:6px;width:56px;height:26px;background:url('/images/bg-top-btn_wev8.png') no-repeat;text-align:center;line-height:26px;color:#000;\">\r\n				\u8fd4\u56de\r\n			</div>\r\n		</a>\r\n		<div id=\"view_title\" style=\"position:absolute;left:65px;top:6px;right:65px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;\">".toCharArray();
    _jsp_string16 = "</div>\r\n	</div>\r\n".toCharArray();
    _jsp_string26 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\">\r\n		<div style=\"width:15px;height:15px;float:left;margin-right: 10px;\"></div>\r\n		<div class=\"ptitle\">\u72b6\u6001</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string23 = "&nbsp;</div>\r\n	</div>\r\n	<div class=\"line\"></div>\r\n	<div class=\"lines\">\r\n		<img src=\"/mobile/plugin/5/images/person_wev8.png\">\r\n		<div class=\"ptitle\">\u53c2\u4f1a\u4eba\u5458</div>\r\n		<div class=\"pcontent\">".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string10 = "&date=".toCharArray();
    _jsp_string2 = "\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n	<meta name=\"author\" content=\"Weaver E-Mobile Dev Group\" />\r\n	<meta name=\"description\" content=\"Weaver E-mobile\" />\r\n	<meta name=\"keywords\" content=\"weaver,e-mobile\" />\r\n	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n	<title>".toCharArray();
    _jsp_string1 = "\r\n\r\n".toCharArray();
  }
}
