/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin._browser;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.hrm.User;
import weaver.general.Util;
import weaver.systeminfo.SystemEnv;
import weaver.hrm.*;
import weaver.file.FileUpload;

public class _mutilcategorybrowser__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.docs.category.SecCategoryComInfo SecCategoryComInfo;
      SecCategoryComInfo = (weaver.docs.category.SecCategoryComInfo) pageContext.getAttribute("SecCategoryComInfo");
      if (SecCategoryComInfo == null) {
        SecCategoryComInfo = new weaver.docs.category.SecCategoryComInfo();
        pageContext.setAttribute("SecCategoryComInfo", SecCategoryComInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.category.SubCategoryComInfo SubCategoryComInfo;
      SubCategoryComInfo = (weaver.docs.category.SubCategoryComInfo) pageContext.getAttribute("SubCategoryComInfo");
      if (SubCategoryComInfo == null) {
        SubCategoryComInfo = new weaver.docs.category.SubCategoryComInfo();
        pageContext.setAttribute("SubCategoryComInfo", SubCategoryComInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet RecordSet;
      RecordSet = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet");
      if (RecordSet == null) {
        RecordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet", RecordSet);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.mobile.browser.BrowserService BrowserService;
      BrowserService = (weaver.mobile.browser.BrowserService) pageContext.getAttribute("BrowserService");
      if (BrowserService == null) {
        BrowserService = new weaver.mobile.browser.BrowserService();
        pageContext.setAttribute("BrowserService", BrowserService);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
FileUpload fu = new FileUpload(request);
request.setCharacterEncoding("UTF-8");
response.setContentType("text/html;charset=UTF-8");
  
  User user = HrmUserVarify.getUser(request , response);
  if(user==null){
	  out.println("\u767b\u9646\u8d85\u65f6,\u8bf7\u91cd\u65b0\u767b\u9646!");
	  return ;
  }

      out.write(_jsp_string3, 0, _jsp_string3.length);
      
int uid=user.getUID();
String type=Util.null2String(request.getParameter("nodetype"));
String id=Util.null2String(request.getParameter("id"));

String para=Util.null2String(request.getParameter("para"));
String isRemember = "false";
String remeStr = "" ;
String mainCateStr = ",";
String subCateStr = ",";
if(!"".equals(para) && !"0".equals(para) && !"remember0".equals(para)){
	if(para.startsWith("remember")){
		para = para.substring(8);
	}
	isRemember = "true";
	String[] secFieldIdArray=Util.TokenizerString2(para,",");
	for(int strIndex=0;strIndex<secFieldIdArray.length;strIndex++){
		String tempSecFieldId = secFieldIdArray[strIndex];
		remeStr +="secField_"+tempSecFieldId+".parentElement.getElementsByTagName(\"INPUT\")[0].checked=true;"
				+"secField_"+tempSecFieldId+".style.color='red';";
				
		String tempSubFieldId = SecCategoryComInfo.getSubCategoryid(tempSecFieldId);
		subCateStr += tempSubFieldId+",";
		mainCateStr += SubCategoryComInfo.getMainCategoryid(tempSubFieldId)+",";
	}
}
String treeDocFieldIds="";
String needPeop="";
Cookie[] cks= request.getCookies();
String rem=null;   
String nodeid=null;
String nodeids=null;
/*
for(int i=0;i<cks.length;i++){
	//System.out.println("ck:"+cks[i].getName()+":"+cks[i].getValue());
if(cks[i].getName().equals("doclistmulti"+uid)){
  rem=cks[i].getValue();
  break;
}
}
*/
if(rem!=null&&rem.length()>1)
nodeids=rem.substring(1);
if(nodeids!=null){
 if(nodeids.indexOf("|")>-1){
  nodeid=nodeids.substring(nodeids.lastIndexOf("|")+1);
 }else
  nodeid=nodeids;
}

boolean exist=true;

String[] ids=Util.TokenizerString2(nodeids,"|");


String splitflag=Util.null2String(request.getParameter("splitflag"));
if("".equals(splitflag)) splitflag = ",";

if("".equals(para)) {
	para = Util.null2String(request.getParameter("selectids"));
}


      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((id));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((type));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((SystemEnv.getHtmlLabelName(33092,user.getLanguage())));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((SystemEnv.getHtmlLabelName(19323,user.getLanguage())));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((SystemEnv.getHtmlLabelName(826,user.getLanguage())));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((SystemEnv.getHtmlLabelName(311,user.getLanguage())));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((SystemEnv.getHtmlLabelName(201,user.getLanguage())));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((isRemember));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((para));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((para));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((para));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((BrowserService.getAllDocCategories(user, para) ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((SystemEnv.getHtmlLabelName(19324,user.getLanguage())));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((SystemEnv.getHtmlLabelName(19323,user.getLanguage())));
      out.write(_jsp_string18, 0, _jsp_string18.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/browser/MutilCategoryBrowser.jsp"), 323825542812811030L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/browser/MobileInit.jsp"), 1397717249655627205L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  private final static char []_jsp_string17;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  private final static char []_jsp_string15;
  private final static char []_jsp_string14;
  private final static char []_jsp_string16;
  private final static char []_jsp_string7;
  private final static char []_jsp_string18;
  private final static char []_jsp_string9;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  static {
    _jsp_string8 = "</div>\r\n                                		</td>\r\n                                	</tr>\r\n                                      <TR>\r\n                                          <TD height=430 colspan=\"4\" width=\"500\" nowrap=\"nowrap\">                                            \r\n                                                <div id=\"deeptree\" style=\"height:100%;width:100%;overflow:scroll;\">\r\n	                                            	<ul id=\"ztreedeep\" class=\"ztree\"></ul>\r\n	                                            </div>                                             \r\n                                          </TD>\r\n                                      </TR>                                    \r\n                                </TABLE>\r\n                                </div>\r\n                                <div style=\"height: 40px;padding-top: 25px;\" align=\"center\">\r\n                                    <BUTTON type=\"button\" class=btn accessKey=O  id=btnok onclick=\"onSave()\"><U>O</U>-".toCharArray();
    _jsp_string4 = "\r\n\r\n\r\n<BODY style=\"overflow-y: hidden;padding: 0px;margin: 0px;\">\r\n    <table width=100% height=100% border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <colgroup>\r\n        <col width=\"10\">\r\n        <col width=\"\">\r\n        <col width=\"10\">\r\n        <tr>\r\n            <td ></td>\r\n            <td valign=\"top\">\r\n                <TABLE class=Shadow style=\"width: 100%\">\r\n                    <tr>\r\n                        <td  valign=\"top\">\r\n                            <FORM NAME=select STYLE=\"margin-bottom:0\" action=\"CategoryBrowser.jsp\" method=post>\r\n							<input class=inputstyle type=hidden name=id value=\"".toCharArray();
    _jsp_string17 = "\");\r\n			} else {\r\n				$(this).removeClass(\"open\").html(\"".toCharArray();
    _jsp_string10 = "</BUTTON>\r\n                                    <BUTTON type=\"button\" class=btnReset accessKey=T  id=btncancel onclick=\"window.parent.close()\"><U>T</U>-".toCharArray();
    _jsp_string5 = "\">\r\n							<input class=inputstyle type=hidden name=type value=\"".toCharArray();
    _jsp_string6 = "\">\r\n                                <div style=\"height: 463px;\">\r\n                                <TABLE  ID=BrowseTable class=\"BroswerStyle\"  cellspacing=\"1\" STYLE=\"margin-top:0;TABLE-LAYOUT:fixed;word-break:break-all\" width=\"100%\">\r\n                                	<TR class=Line1><TH colspan=\"4\" ></TH></TR>\r\n                                	<tr><td colspan=\"4\">\r\n                                		<span style=\"font-weight: bold;padding-left: 7px;float: left;padding-top: 9px;\">".toCharArray();
    _jsp_string13 = "\";\r\n	var cxtree_id = \"".toCharArray();
    _jsp_string15 = "\";\r\n		cxtree_ids = cxtree_id.split(',');\r\n		cxtree_id = cxtree_ids[0];\r\n	}\r\n	\r\n	//zTree\u914d\u7f6e\u4fe1\u606f\r\n	var setting = {\r\n		check: {\r\n			enable: true,       //\u542f\u7528checkbox\u6216\u8005radio\r\n			chkStyle: \"checkbox\",  //check\u7c7b\u578b\u4e3acheckbox\r\n			chkboxType: { \"Y\":\"\", \"N\": \"\"} \r\n		},\r\n		view: {\r\n			expandSpeed: \"\"     //\u6548\u679c\r\n		},\r\n		callback: {\r\n			onClick: zTreeOnClick,   //\u8282\u70b9\u70b9\u51fb\u4e8b\u4ef6\r\n			onCheck: zTreeOnCheck\r\n		}\r\n	};\r\n\r\n	var zNodes = ".toCharArray();
    _jsp_string14 = "\";\r\n	var cxtree_ids;\r\n	if(selectedids!=\"0\"&&selectedids!=\"\"){\r\n		cxtree_id = \"".toCharArray();
    _jsp_string16 = ";\r\n	\r\n	$(document).ready(function(){\r\n		//\u521d\u59cb\u5316zTree\r\n		var treeObj = $.fn.zTree.init($(\"#ztreedeep\"), setting, zNodes);\r\n		var nodes = treeObj.getCheckedNodes(true);\r\n		for(var i=0; i<nodes.length; i++) {\r\n			expendParentNode(treeObj, nodes[i]);\r\n		}\r\n		\r\n		$(\"#selectAll\").click(function(){\r\n			selectallflag = !selectallflag;\r\n			var treeObj = $.fn.zTree.getZTreeObj(\"ztreedeep\");\r\n			var type = { \"Y\":\"\", \"N\": \"\"};\r\n			if(selectallflag) type = { \"Y\":\"s\", \"N\": \"s\"};\r\n			treeObj.setting.check.chkboxType = type;\r\n			if(selectallflag) {\r\n				$(this).addClass(\"open\").html(\"".toCharArray();
    _jsp_string7 = "</span>\r\n                                		<div id=\"selectAll\" style=\"\">".toCharArray();
    _jsp_string18 = "\");\r\n			}\r\n		});\r\n	});\r\n	\r\n	function expendParentNode(treeObj, node) {\r\n		var parentNode = node.getParentNode();\r\n		if(!parentNode || parentNode.open == true) return;\r\n		treeObj.expandNode(parentNode, true);\r\n		expendParentNode(treeObj, parentNode);\r\n	}\r\n	\r\n	function zTreeOnClick(event, treeId, treeNode) {\r\n	    var treeObj = $.fn.zTree.getZTreeObj(treeId);\r\n	    if (treeNode.isParent) {\r\n			treeObj.expandNode(treeNode);\r\n		}\r\n	};\r\n	\r\n	function onSaveJavaScript(){\r\n	    var nameStr=\"\";\r\n	    var idStr = \"\";\r\n	    var treeObj = $.fn.zTree.getZTreeObj(\"ztreedeep\");\r\n		var nodes = treeObj.getCheckedNodes(true);\r\n		\r\n		if (nodes == undefined || nodes == \"\" || nodes.length < 1) {\r\n			return \"\";\r\n		}\r\n		\r\n		for (var i=0; i<nodes.length; i++) {\r\n			nameStr += \",\" + nodes[i].name;\r\n			idStr += \",\" + nodes[i].nodeValue;\r\n		}\r\n		\r\n		resultStr = encodeURIComponent(idStr) + \"$\" + encodeURIComponent(nameStr);\r\n	    return resultStr;\r\n	}\r\n	\r\n	function onSave() {\r\n    	var  trunStr = \"\", returnVBArray = null;\r\n	    trunStr =  onSaveJavaScript();\r\n	    if(trunStr != \"\") {\r\n			returnVBArray = trunStr.split(\"$\");\r\n			var returnjson = {id:decodeURIComponent(returnVBArray[0]), name:decodeURIComponent(returnVBArray[1])};\r\n	        window.parent.returnValue  = returnjson;\r\n	        window.parent.close();\r\n	    } else {\r\n	        window.parent.close();     \r\n		}\r\n    }\r\n    \r\n    function onClear() {\r\n	    window.parent.returnValue = {id:\"\", name:\"\"};\r\n	    window.parent.close();\r\n	}\r\n	\r\n	function zTreeOnCheck(event, treeId, treeNode) {\r\n		if(!selectallflag) return;\r\n		var treeObj = $.fn.zTree.getZTreeObj(treeId);\r\n		treeObj.expandNode(treeNode, true, true);\r\n	}\r\n	//-->\r\n</SCRIPT>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string9 = "</BUTTON>\r\n	                                <BUTTON type=\"button\" class=btn accessKey=2  id=btnclear onclick=\"onClear()\"><U>2</U>-".toCharArray();
    _jsp_string2 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n \r\n\r\n".toCharArray();
    _jsp_string12 = "\";\r\n	var selectedids = \"".toCharArray();
    _jsp_string3 = "\r\n<HTML>\r\n<HEAD>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n    <link href=\"/mobile/plugin/browser/css/Weaver_wev8.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n    <script type=\"text/javascript\" src=\"/mobile/plugin/browser/js/zTree/js/jquery-1.4.4.min_wev8.js\"></script>\r\n	<link rel=\"stylesheet\" href=\"/mobile/plugin/browser/js/zTree/css/zTreeStyle/zTreeStyle_wev8.css\" type=\"text/css\">\r\n	<script type=\"text/javascript\" src=\"/mobile/plugin/browser/js/zTree/js/jquery.ztree.core-3.1.min_wev8.js\"></script>\r\n	<script type=\"text/javascript\" src=\"/mobile/plugin/browser/js/zTree/js/jquery.ztree.excheck-3.1.min_wev8.js\"></script>\r\n	<style>\r\n		.ztree span{\r\n			word-break:break-all;\r\n		}\r\n		\r\n		.ztree li button.ico_docu {\r\n			background-position: -80px 0;\r\n		}\r\n		\r\n		#selectAll {\r\n			display: inline-block;\r\n			float: right;\r\n			color: #1098ff;\r\n			border: 1px solid #aecef1;\r\n			padding: 0 10px;\r\n			height: 23px;\r\n			line-height: 23px;\r\n			cursor: pointer;\r\n		}\r\n		\r\n		div#selectAll.open {\r\n			color: #ffffff;\r\n			background-color: #1098ff;\r\n		}\r\n	</style>\r\n</HEAD>\r\n\r\n".toCharArray();
    _jsp_string11 = "</BUTTON>\r\n                                </div>\r\n                            </FORM>\r\n                         </td>\r\n                    </tr>\r\n                </TABLE>\r\n            </td>\r\n            <td></td>\r\n        </tr>\r\n    </table>\r\n</BODY>\r\n</HTML>\r\n\r\n<script type=\"text/javascript\">\r\n\r\n	//<!--\r\n	var selectallflag=false;\r\n	var isremember = \"".toCharArray();
  }
}
